name: Test

permissions:
  contents: write

on: [push]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

defaults:
  run:
    shell: bash --noprofile --norc -CeEuo pipefail {0}

jobs:
  rust-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-latest, macos-15]
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 23
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: cargo -q  test
        run: |
          cargo -q  test
      - name: cargo -q  run
        run: |
          cargo -q  run -- --version
      - name: install
        run: |
          for file in dist-manifest/*.json; do
            echo $file
            cargo -q  run -- $file
            source ~/.bashrc
          done

      - name: install list
        run: |
          cat assets/url-list.txt | while read line
          do
              echo $line
              [[ -z "$line" ]] && continue
              cargo -q  run -- $line
          done

      - name: install alias qjs-next
        run: |
          cargo -q  run -- https://github.com/quickjs-ng/quickjs --name qjs --alias qjs-next

      - name: test which
        if: matrix.os != 'windows-latest'
        run: |
          ls -lh ~/.ei
          cat assets/${{ matrix.os }}.txt | while read line
          do
              echo $line
              [[ -z "$line" ]] && continue
              # ls -lh ~/.ei/$line
              which $line
          done
      - name: test which on windows
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: |
          Get-Content "assets/${{ matrix.os }}.txt" | ForEach-Object {
              Write-Output $_
              Get-Command $_
          }

  js-test:
    if: "!startsWith(github.ref, 'refs/tags/')"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-latest, macos-15]
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 23
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: vitest
        run: |
          pnpm install
          pnpm run build
      - name: install
        run: |
          for file in dist-manifest/*.json; do
            echo $file
            node cli/cli.js "$file"
            source ~/.bashrc
          done

      - name: install list
        run: |
          cat assets/url-list.txt | while read line
          do
              echo $line
              [[ -z "$line" ]] && continue
              node cli/cli.js "$line"
          done

      # - name: install alias qjs-next
      #   run: |
      #     cr -- https://github.com/quickjs-ng/quickjs --name qjs --alias qjs-next

      - name: test which
        if: matrix.os != 'windows-latest'
        run: |
          ls -lh ~/.ei

          cat assets/${{ matrix.os }}.txt | while read line
          do
              echo $line
              [[ -z "$line" ]] && continue
              # ls -lh ~/.ei/$line
              which $line
          done
      - name: test which on windows
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: |
          Get-Content "assets/${{ matrix.os }}.txt" | ForEach-Object {
              Write-Output $_
              Get-Command $_
          }
